[package]
name = "gender-lang"
version = "0.1.0"
authors = ["Arthur Goldman <arthur@goldman-tribe.org>"]
edition = "2018"

[dependencies]
lazy_static = "1.3"
lalrpop-util = "0.17"
regex = "1.1"

[build-dependencies]
lalrpop = "0.17"
